version: '3'
services:
  db:
    image: mysql:latest
    restart: always
    container_name: teste_db_container
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: db_test
      MYSQL_PASSWORD: root
    ports:
      - "3306:3306"